name: Deploy

on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
        default: prod
    secrets:
      NEXT_PUBLIC_MORALIS_API_KEY:
        required: true
      APP_DOMAIN:
        required: true
      NEXTAUTH_URL:
        required: true
      NEXTAUTH_SECRET:
        required: true
  push:
    branches:
      - main

concurrency: deploy-main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          envName: prod
      - name: Build app bundle
        run: |
          cd frontend
          yarn install --frozen-lockfile
          echo NEXT_PUBLIC_MORALIS_API_KEY=${{ secrets.NEXT_PUBLIC_MORALIS_API_KEY }} >> .env
          echo APP_DOMAIN=${{ secrets.APP_DOMAIN }} >> .env
          echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env
          echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env
          export NODE_OPTIONS="--max-old-space-size=4096"
          CI= yarn build
      - name: Build CDK app stack
        run: |
          cd infra
          yarn install
          yarn build
      - name: Deploy App
        run: |
          cd infra
          export AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}"
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          node_modules/.bin/cdk deploy --require-approval never --ci
